version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/shared-security"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/auth-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/chat-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/eureka-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/media-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/post-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/recommend-service/java-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/user-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/client-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/admin-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/recommend-service/python-model"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
